### ISSUE TITLE
Necro-Issue

### ISSUE THREAD

**Issue by y0himba** [SilverAzide/Alien#2]
Sorry, but I have only just discovered this skin, and it is PERFECTION for my desktop!  

Issue: Like many skins lately, the weather isn't working.  

I also need to figure out how to add more drives. 

Can an update be made to repair the weather?  

I cannot believe I just found this.

**Comment by y0himba** [comment]
Never mind.  I downloaded it form Rainmeter forums and that was pointing to 1.2.0.  I grabbed 1.2.1 from her and it is working.

**Comment by SilverAzide** [comment]
Glad you are enjoying the skin!  Thanks for the feedback, I will fix the link to point to the latest version...
